import turtle

turtle.title('数学题1')
turtle.up()
turtle.goto(0, 100)
turtle.down()
turtle.write("A", font=('宋体', 10, 'normal'))
turtle.hideturtle()
turtle.pencolor("red")
turtle.seth(-130)
turtle.fd(261.08)
turtle.pencolor("black")
turtle.fd(138.92)

turtle.write("B", font=('宋体', 10, 'normal'))
turtle.seth(70)
turtle.fd(138.92)
turtle.pencolor("red")
turtle.fd(261.08)

turtle.pencolor("black")
turtle.write("C", font=('宋体', 10, 'normal'))
turtle.seth(-30)
turtle.fd(138.92)
turtle.pencolor("red")
turtle.fd(261.08)

turtle.pencolor("black")
turtle.seth(190)
turtle.write("D", font=('宋体', 10, 'normal'))
turtle.fd(138.92)
turtle.pencolor("red")
turtle.fd(261.08)
turtle.pencolor("black")
turtle.write("E", font=('宋体', 10, 'normal'))
turtle.up()
turtle.goto(-40, 20)
turtle.write("已知:黑红线段各自相等", font=('宋体', 10, 'normal'))
turtle.goto(-40, 0)
turtle.write("求角EAD的大小?", font=('宋体', 10, 'normal'))
turtle.done()
